### ISSUE TITLE
new_soc computation in _update_status

### ISSUE THREAD

**Issue by linker81** [Total-RD/pymgrid#100]
In the _update_status function in Microgrid class, the new_soc is computed as follow:

```
new_soc = df['battery_soc'][-1] + (control_dict['battery_charge']*self.parameters['battery_efficiency'].values[0]
                                                        - control_dict['battery_discharge'] / self.parameters['battery_efficiency'].values[0]) / self.parameters['battery_capacity'].values[0]
```

I think that the correct implementation is the following:

```
new_soc = df['battery_soc'][-1] + (control_dict['battery_charge']*self.parameters['battery_efficiency'].values[0]
                                                        - control_dict['battery_discharge'] * self.parameters['battery_efficiency'].values[0]) / self.parameters['battery_capacity'].values[0]
```

In other words, I think that the battery discharge value has to be multiplied to the battery efficiency and not divided by it.

**Comment by ahalev** [comment]
This is not a typo, but it is possible that the underlying equation is implemented incorrect. Will check.

**Comment by ahalev** [comment]
Updated with a fix. This code is also set to be refactored at some point in the future.

**Comment by ahalev** [comment]
This code was correct originally and has been reverted. Discharging amount x requires decreasing battery charge by x/efficiency, which is > x.
