### ISSUE TITLE
Unable to run Q learning Example

### ISSUE THREAD

**Issue by Akash-Ravichandan** [Total-RD/pymgrid#103]
Unable to run the Q learning example, irrespective of changing the horizon values.  While running the benchmark.describe() key error occurs for cost. Kindly help.
![Error1](https://user-images.githubusercontent.com/98386785/159147677-654a0900-cc06-4a93-91e6-29ea81ad2868.png)
![Error2](https://user-images.githubusercontent.com/98386785/159147678-08fc641c-c626-40c7-b780-79bcfebf34ee.png)

**Comment by ahalev** [comment]
I will look into this. The second notebook is close to deprecated at this point as it doesn't really to pigenhole our clearly continuous actions into a tabular DQN, so that may stay as-is.

**Comment by ahalev** [comment]
Should be fixed as of this pull request.
