### ISSUE TITLE
Configure time series

### ISSUE THREAD

**Issue by mdeboute** [Total-RD/pymgrid#109]
Can we generate time series with a time step of 10 minutes and change the time horizon? I have changed the default parameter `timestep=1` in the constructor of the `MicrogridGenerator` object but nothing changes. It seems like the `timestep` parameter can't be a float but even if we test with another integer value like 2 (for 2 hours) it doesn't work/change anything.

Example:

```python
m_gen = mg.MicrogridGenerator(
        nb_microgrid=1,
        random_seed=random.randint(0, 100),
        timestep=2,
    )
m_gen.generate_microgrid(verbose=False)
microgrid = m_gen.microgrids[0]
pv_ts = microgrid._pv_ts
print(pv_ts)
```

**Comment by ahalev** [comment]
Circling back to this very late @mdeboute. Are you still looking for this feature? If so, let me know if the new `Microgrid` class can accomplish what you are looking for. You can define any/all of the subclasses of `BaseTimeseriesMicrogridModule`: `RenewableModule`, `LoadModule`, and `GridModule`, and pass them a time series of your choosing. Thus one time step is simply the difference between rows the time series you pass to these modules.

**Comment by mdeboute** [comment]
Thank you for your feedback, better late than never ;)! I no longer work at Total and therefore I no longer use this tool but I will try to see if it works when I have time and I will say if it is fixed now!
