### ISSUE TITLE
error while running "A Q-Learning implementation for PymGrid"

### ISSUE THREAD

**Issue by AIX2** [Total-RD/pymgrid#61]
While running this block:
"for i in range(env.nb_microgrids):
    print("Microgrid", i,":")
    env.microgrids[i].compute_benchmark("rule_based")"

I received this error:

"Microgrid 0 :
In Progress 0% 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-c98b9321e4b7> in <module>()
      1 for i in range(env.nb_microgrids):
      2     print("Microgrid", i,":")
----> 3     env.microgrids[i].compute_benchmark("rule_based")

2 frames
/usr/local/lib/python3.6/dist-packages/pymgrid/Microgrid.py in _run_priority_based(self, load, pv, parameters, status, priority_dict)
   1393                     capa_to_charge = max(
   1394                         (parameters['battery_soc_max'].values[0] * parameters['battery_capacity'].values[0] -
-> 1395                        status['battery_soc'].iloc[-1] *
   1397                          parameters['battery_capacity'].values[0]

AttributeError: 'list' object has no attribute 'bloc'"

**Comment by GonzagueHenri** [comment]
Hello,

I have updated the notebook and should be working properly now. Let me know if it works on your side.

Thanks,
Gonzague
