### ISSUE TITLE
404 on DOE/NREL/ALLIANCE provided linke

### ISSUE THREAD

**Issue by utix** [Total-RD/pymgrid#64]
The link provided into the [README.md file ](https://github.com/Total-RD/pymgrid#data) is answering with a 404 error
[broken link](https://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/tmy3/)

**Comment by GonzagueHenri** [comment]
Should be fixed now

**Comment by utix** [comment]
Fixed by 8aa6fa5dc86341af766b3b062bf0dbb9403665b2 

thanks
