### ISSUE TITLE
Error in " A Q-Learning implementation for PymGrid" notebook

### ISSUE THREAD

**Issue by adityauser** [Total-RD/pymgrid#82]
After running the cell 
`Q1 = training_Q_Learning(mg0,48)`
I'm getting error: 
```
KeyError                                  Traceback (most recent call last)
<ipython-input-25-3310e8e5f54d> in <module>
----> 1 Q1 = training_Q_Learning(mg0,48)

<ipython-input-23-06ae1e9f9115> in training_Q_Learning(mg, horizon)
     76             soc = round(mg.battery.soc,1)
     77             s_ = (net_load, soc)
---> 78             a_ = max_dict(Q[s_])[0]
     79 
     80             if i == horizon-1:

KeyError: (171, 0.9)
```
This indicates that `Q` is not defined for (171, 0.9) pair. 
I found that the value of `mg0.forecast_load().max()` is 160. Then how are me getting (171, 0.9) as one of the states?
Can you please tell me how to resolve this error?

Any help will be appreciated.

**Comment by GonzagueHenri** [comment]
forecast_load() will return the load over the mg.horizon so if the horizon is 24 then you will not get the values between 24 and 48 in your case. You can get the max load in mg.parameters['load'].

Hope this helps.
Gonzague
