### ISSUE TITLE
Bug with the genset in Environment.py

### ISSUE THREAD

**Issue by Pierrick-Pochelu** [Total-RD/pymgrid#83]
In the file:
https://github.com/Total-RD/pymgrid/blob/master/src/pymgrid/Microgrid.py 
line 213 is: 
control_dict['genset'] = max(0, action[4] * min(action[5] * mg.genset.rated_power_import))

It seems that the function min is badly used (1 arg instead of 2) and the genset object does not contain rated_power_import.  The same problem occurs in the branch gonzague_dev.

Do you confirm that the correct line should be ?
control_dict['genset'] = max(0, action[4] * min(action[5] * mg.genset.rated_power, mg.genset.rated_power))

Thank you,

Pierrick

**Comment by GonzagueHenri** [comment]
Hello Pierrick,

I think you are right, do you mind making the change and creating a pull request?

Thanks,
Gonzague
