### ISSUE TITLE
Can we use this, for real world projects simulations?

### ISSUE THREAD

**Issue by msbomrel2020** [Total-RD/pymgrid#90]
Actually, I am working on micro grid software. I was wondering if this can be used for simulation of real-world projects. I am confused as it's readme says that we should cite it if we are using it for research purpose.

**Comment by GonzagueHenri** [comment]
Hello,

Yes! You can refer to the license to know more about the conditions of utilization https://github.com/Total-RD/pymgrid/blob/master/LICENSE
